UniTap-BackEnd/config/routes.rb
Rails.application.routes.draw do
  #resources :company_cards
  #resources :company_cards
  #resources :company_cards
  #resources :company_cards
  #resources :cards
  namespace :api do
    resources :company_cards do
      resources :company_cards, only: [:create, :update, :destroy]
    end
  end
end

UniTap-BackEnd/app/models/company_card.rb
class CompanyCard < ActiveRecord::Base
end

UniTap-BackEnd/app/controllers/api/company_cards_controller.rb
class Api::CompanyCardsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    if !(params[:cardhash].nil? || params[:phonecrc].nil?)
  	  if !(CompanyCard.find_by(cardhash: params[:cardhash], phonecrc: params[:phonecrc]).nil?)
        render status: 200, json: {
          message: "Welcome to our business!"
        }
      else
        render status: 422, json: {
          message: "Request Denied."
        }
      end
    elsif !(params[:id].nil?)
      if(CompanyCard.exists?(params[:id]))
        card = CompanyCard.find(params[:id])
        render status: 200, json: {
          company_cards: card
        }.to_json
      end
    elsif !(params[:cardhash].nil?) || !(params[:phonecrc].nil?)
      render status: 422, json:{
        message: "Your request makes no sense."
      }
    else
      render status: 200, json: CompanyCard.all

    end

  end
  
  ##
  # display a particular card
  #
  def show
  	if(!params[:id].nil?)
      if(CompanyCard.exists?(params[:id]))
        card = CompanyCard.find(params[:id])
        render status: 200, json: {
        company_cards: card
      }.to_json
      
      else
        render status: 422, json: {
          message: "Unable to process your request of the server."
        }.to_json
      end
    else
        render status: 422, json: {
          message: "Unable to process your request of the server."
        }.to_json
    end
  end

  ##
  # Create a new card for the company's database
  #
  def create
    if !(params[:cardhash].nil? || params[:phonecrc].nil?)
      if !(CompanyCard.find_by(cardhash: params[:cardhash], phonecrc: params[:phonecrc]).nil?)
        render status: 200, json: {
          message: "Welcome to our business!"
        }
      else
        render status: 422, json: {
          message: "Request Denied."
        }
      end
    elsif !(params[:id].nil?)
      if(CompanyCard.exists?(params[:id]))
        card = CompanyCard.find(params[:id])
        render status: 200, json: {
          company_cards: card
        }.to_json
      end
    elsif !(params[:cardhash].nil?) || !(params[:phonecrc].nil?)
      render status: 422, json:{
        message: "Your request makes no sense."
      }
    else
      render status: 200, json: CompanyCard.all

    end
    #if (params[:cardhash].nil?) || (params[:phonecrc].nil?)
    #  render status: 422, json: {
    #    message: "Card format incorrect.",
    #  }.to_json
    #else
    #  card = CompanyCard.new(card_params)
    #  if card.save
    #    render status: 200, json: {
    #      message: "Successfully created your card.",
    #      company_cards: card
    #    }.to_json
    #  else
    #    render status: 422, json: {
    #   	  message: "Unable to process your request of the server."
    #    }.to_json
  	#  end
    #end

  end

  ##
  # Delete a certain card in the database
  #
  def destroy
    if !(params[:id].nil?)
      if (CompanyCard.exists?(params[:id]))
        card = CompanyCard.find(params[:id])
        card.destroy
        render status: 200, json:{
          message: "Successfully deleted that card."
        }.to_json
      else
        render status: 422, json:{
          message: "Unable to process your request of the server."
        }.to_json 
      end
    else
      render status: 422, json:{
        message: "Unable to process your request of the server."
      }.to_json 
    end
  end
  
  ##
  # Update a certain card in the company's database
  #
  def update
    if !(params[:id].nil?)
      if(CompanyCard.exists?(params[:id]))
        card = CompanyCard.find(params[:id])
        card.update(card_params)
        render status: 200, json:{
          message: "Successfully updated",
          company_cards: card
        }.to_json
      else
        render status: 422, json:{
          message: "Unable to process your request of the server."
        }.to_json
      end
    else
      render status: 422, json:{
          message: "Unable to process your request of the server."
        }.to_json
    end
  end

  ##
  # List of parameters that the api request is allowed to present the server
  #
  private
  def card_params
    params.permit(:company_card, :userid, :cardhash, :phonecrc)
  end
end

UniTap-BackEnd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

UniTap-BackEnd/app/controllers/company_cards_controller.rb
class CompanyCardsController < ApplicationController
  before_action :set_company_card, only: [:show, :edit, :update, :destroy]

  # GET /company_cards
  # GET /company_cards.json
  def index
    @company_cards = CompanyCard.all
  end

  # GET /company_cards/1
  # GET /company_cards/1.json
  def show
  end

  # GET /company_cards/new
  def new
    @company_card = CompanyCard.new
  end

  # GET /company_cards/1/edit
  def edit
  end

  # POST /company_cards
  # POST /company_cards.json
  def create
    @company_card = CompanyCard.new(company_card_params)

    respond_to do |format|
      if @company_card.save
        format.html { redirect_to @company_card, notice: 'Company card was successfully created.' }
        format.json { render :show, status: :created, location: @company_card }
      else
        format.html { render :new }
        format.json { render json: @company_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_cards/1
  # PATCH/PUT /company_cards/1.json
  def update
    respond_to do |format|
      if @company_card.update(company_card_params)
        format.html { redirect_to @company_card, notice: 'Company card was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_card }
      else
        format.html { render :edit }
        format.json { render json: @company_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_cards/1
  # DELETE /company_cards/1.json
  def destroy
    @company_card.destroy
    respond_to do |format|
      format.html { redirect_to company_cards_url, notice: 'Company card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_card
      if(params[:id].exists?)
        @company_card = CompanyCard.find(params[:id])
      else(params[:cardhash].exists?)
        if(params[:phonecrc].exists?)
          @company_card = CompanyCard.find_by(cardhash: params[:cardhash], phonecrc: params[:phonecrc])
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_card_params
      #params.require(:company_card).permit(:cardhash, :phonecrc, :activity)
      params.permit(:company_card, :cardhash, :phonecrc)
    end
end

UniTap-BackEnd/app/helpers/application_helper.rb
module ApplicationHelper
end

UniTap-BackEnd/app/helpers/company_cards_helper.rb
module CompanyCardsHelper
end

UniTap-BackEnd/app/views/company_cards/_form.html.erb
<%= form_for(@company_card) do |f| %>
  <% if @company_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_card.errors.count, "error") %> prohibited this company_card from being saved:</h2>

      <ul>
      <% @company_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :cardhash %><br>
    <%= f.text_field :cardhash %>
  </div>
  <div class="field">
    <%= f.label :phonecrc %><br>
    <%= f.number_field :phonecrc %>
  </div>
  <div class="field">
    <%= f.label :activity %><br>
    <%= f.number_field :activity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

UniTap-BackEnd/app/views/company_cards/edit.html.erb
<h1>Editing Company Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_card %> |
<%= link_to 'Back', company_cards_path %>

UniTap-BackEnd/app/views/company_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Company Cards</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Cardhash</th>
      <th>Phonecrc</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_cards.each do |company_card| %>
      <tr>
        <td><%= company_card.userid %></td>
        <td><%= company_card.cardhash %></td>
        <td><%= company_card.phonecrc %></td>
        <td><%= company_card.activity %></td>
        <td><%= link_to 'Show', company_card %></td>
        <td><%= link_to 'Edit', edit_company_card_path(company_card) %></td>
        <td><%= link_to 'Destroy', company_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company card', new_company_card_path %>

UniTap-BackEnd/app/views/company_cards/new.html.erb
<h1>New Company Card</h1>

<%= render 'form' %>

<%= link_to 'Back', company_cards_path %>

UniTap-BackEnd/app/views/company_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @company_card.userid %>
</p>

<p>
  <strong>Cardhash:</strong>
  <%= @company_card.cardhash %>
</p>

<p>
  <strong>Phonecrc:</strong>
  <%= @company_card.phonecrc %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @company_card.activity %>
</p>

<%= link_to 'Edit', edit_company_card_path(@company_card) %> |
<%= link_to 'Back', company_cards_path %>

UniTap-BackEnd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UniTapBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>